export const PERSONS_LIST = {
  ADD_PERSON: 'ADD_PERSON',
}

export const FILTER_LIST = {
  SORT_LIST: 'SORT_LIST',
  SEARCH_LIST: 'SEARCH_LIST',
}

export const NEW_PERSON = {
  UPDATE_NEW_PERSON_INFO: 'UPDATE_NEW_PERSON_INFO',
  RESET_PERSON_INFO: 'RESET_PERSON_INFO',
}
